spring:
  datasource:
    url: jdbc:mysql://localhost:33306/stock_example?serverTimezone=Asia/Seoul
    username: root
    password: root01
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 40

  sql.init.mode: never
  jpa:
    hibernate:
      ddl-auto: create  # create, update, validate, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul
    open-in-view: false


logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql: trace
        orm:
          jdbc:
            bind: trace

